networks:
  laravel:

services:
  server:
    build: .
    command: npm run dev
    container_name: serverw
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
      - /var/www/vendor
    depends_on:
      - mysql
    links:
      - mysql
      
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
     - "8082:80"
    volumes: 
     - "./src:/var/www/html"
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
    - php 
    - mysql
    networks:
     - laravel

  mysql:
    image: mysql:8.0.16
    container_name: mysqlq
    restart: unless-stopped
    tty: true
    ports: 
     - "4306:3306"
    volumes: 
     - /var/lib/mysql:/var/lib/mysql
    environment: 
     MYSQL_DATABASE: homestead
     MYSQL_USER: homestead
     MYSQL_PASSWORD: secrt
     MYSQL_ROOT_PASSWORD: secrt
     SERVICE_TAG: dev
     SERVICE_NAME: mysql  
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:8080"
    networks:
      - laravel
  
  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   restart: always
   container_name: phpmyadminf
   depends_on: 
    - mysql
   ports: 
    - "8081:80"
   environment: 
    PMA_HOST: mysql
    MYSQl_ROOT_PASSWORD: secrt
   networks: 
    - laravel


  client:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: clientt
    volumes:
      - ./src:/var/www/
      - /var/www/node_modules
    depends_on:
      - "server"    


  
     
 
           
